name: Test

on:
  pull-requests:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: comment pr
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "[CI] hello"
          comment_includes: "[CI]"
